### ISSUE TITLE
Migrate to webextension

### ISSUE THREAD

**Issue by rybval** [rybval/list_tabs#24]
As Mozilla have deprecated Addon API and going to shut it down in November it is necessary to migrate.

**Comment by pmorch** [comment]
FYI: https://addons.mozilla.org/en-US/firefox/addon/all-tabs-helper/ does something similar already with Web Extensions. I prefer the UI of list_tabs, I just wanted to let you know about the other extension if you needed/wanted to know e.g. what APIs it uses etc. Unfortunately, all-tabs-helper is GPLv3 and not the MIT license, so I guess cut'n'pasting from there is not possible :-)
