### ISSUE TITLE
not working in firefox 66

### ISSUE THREAD

**Issue by alfredoivan** [rybval/list_tabs#25]
It doesn't work in my firefox.
OS: Ubuntu 14.04

**Comment by rybval** [comment]
Could you please describe the issue in detail?
What do you see?
What version of the extension do you use?

**Comment by alfredoivan** [comment]
I can only see to download the following:
it is 2.0.0
Released Sep 30, 2018 - 57.91 KB
Works with firefox 48.0 and later

I have another computer with a different firefox version and it works there. I don't have it atm so i will report later.
This firefox is 66.0.3 (64-bit)  and the list_tabs Version 2.0.0  doesn't install. Message:
"Installation aborted because the add-on appears to be corrupt."

![image](https://user-images.githubusercontent.com/5880102/79081538-c825b400-7cf4-11ea-8c84-00e0c7f36512.png)

**Comment by alfredoivan** [comment]
btw this is what's seen on "Browser Console" when trying to install:

![image](https://user-images.githubusercontent.com/5880102/79081580-2c487800-7cf5-11ea-8e3b-05d4ca6012df.png)

**Comment by alfredoivan** [comment]
update:
it works fine in 57.0.1 (64-bit) .

**Comment by rybval** [comment]
The log suggests that Firefox tries to get `browser_specific_settings.gecko.id` from [manifest.json](https://github.com/rybval/list_tabs/blob/e522a57ed044aa45b457898af2845056dfaad037/manifest.json), which [is not mandatory and should not lead to error if missing](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings). Extension does work without this property in my Firefox 75.0 as well as yours Firefox 57.0.1.

I'm afraid the only thing I can suggest is to reinstall Firefox (too bad, Firefox 66.0.3 is the last version for Ubuntu 14.04).

Have you experienced the same issue with any other extension?

I will try to update the manifest and add the `browser_specific_settings.gecko.id` soon.

**Comment by rybval** [comment]
@alfredoivan , could you please try installing the extension one more time? 
https://addons.mozilla.org/ru/firefox/addon/list-tabs/

**Comment by alfredoivan** [comment]
> @alfredoivan , could you please try installing the extension one more time?
> https://addons.mozilla.org/ru/firefox/addon/list-tabs/

Hello.
It worked. Issue solved.
